http_port 3128
acl SSL_ports port 443
acl CONNECT method CONNECT
acl allowlist dstdomain "/etc/squid/allowlist.txt"
http_access deny CONNECT !SSL_ports
http_access allow CONNECT allowlist
http_access allow allowlist
http_access deny all

cache_peer host.docker.internal parent 7890 0 no-query no-digest default
never_direct allow all

logformat sbx %ts.%03tu %un %>a %Ss/%>Hs %rm %ru %Sh/%<a
access_log stdio:/var/log/squid/access.log sbx
cache deny all
